schedule:
  kind: IntervalSchedule
  args:
    interval: 15s
samplers:
  - kind: DaskK8Cluster
  - kind: DaskPromScheduler
watchers:
  - kind: k_calibrate.watchers:DaskWatcher
stop_criteria:
  kind: 'builtin:after_iterations'
  args:
    amount: 200